apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
    - name: workspace
  steps:
    - name: lint
      image: golangci/golangci-lint:v1.50.0
      command:
        - sh
        - -c
      args:
        - |
          echo "Lint task start ...."
          ls
          golangci-lint run ./...
        
