apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
    - name: workspace
  steps:
    - name: lint
      image: golangci/golangci-lint:v1.42
      command:
        - sh
        - -c
      args:
        - |
          golangci-lint run ./...
